tag @s remove soulpotion
tag @s remove hellpotion
tag @s remove underworldpotion
tag @s remove smokepotion
tag @s remove skypotion
tag @s remove ghastpotion
tag @s remove minerpotion
tag @s remove beaconpotion
tag @s remove sunpotion
tag @s remove lightpotion
tag @s remove tornadopotion
tag @s remove undyingpotion
tag @s remove choruspotion
tag @s remove nopoisonpotion
tag @s remove frostpotion
tag @s remove soulvisionpotion
tag @s remove voidpotion
tag @s remove limbopotion
tag @s remove drunkpotion